#pragma once

#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <string>

#ifdef ARK_EXPORTS
#define ARK_API __declspec(dllexport)
#else
#define ARK_API __declspec(dllimport)
#endif

// Forward declarations
struct AActor;
struct ABrush;
struct ACharacter;
struct AController;
struct ACustomActorList;
struct ACustomGameMode;
struct ADayCycleManager;
struct ADestroyedMeshActor;
struct ADirectionalLight;
struct ADroppedItem;
struct ADroppedItemEgg;
struct ADroppedItemLowQuality;
struct AEmitter;
struct AGameMode;
struct AGameModeBase;
struct AGameNetworkManager;
struct AGameSession;
struct AGameState;
struct AHibernationManager;
struct AHUD;
struct AInfo;
struct ALevelScriptActor;
struct AMatineeActor;
struct AMatineeActorManager;
struct AMissionDispatcher;
struct AMissionType;
struct ANPCZoneManager;
struct ANPCZoneVolume;
struct AOceanDinoManager;
struct AOceanHarvestManager;
struct AOceanVolume;
struct APawn;
struct APhysicsVolume;
struct APlayerCameraManager;
struct APlayerController;
struct APlayerStart;
struct APlayerState;
struct APointOfInterestCosmeticActor {};
struct APointOfInterestManagerList;
struct APostProcessVolume;
struct APrimalBuff_Grappled;
struct APrimalBuff_MissionData;
struct APrimalBuff;
struct APrimalCharacter;
struct APrimalDinoAIController;
struct APrimalDinoCharacter;
struct APrimalEmitterSpawnable;
struct APrimalPlayerController;
struct APrimalProjectileBoomerang;
struct APrimalProjectileGrapplingHook;
struct APrimalRaft;
struct APrimalStructure;
struct APrimalStructureClaimFlag;
struct APrimalStructureDoor;
struct APrimalStructureElevatorPlatform;
struct APrimalStructureExplosive;
struct APrimalStructureExplosiveTransGPS;
struct APrimalStructureItemContainer_CropPlot;
struct APrimalStructureItemContainer_SupplyCrate;
struct APrimalStructureItemContainer;
struct APrimalStructureLadder;
struct APrimalStructureMovingContainer;
struct APrimalStructurePlacer;
struct APrimalStructureSail;
struct APrimalStructureSeating_DriverSeat;
struct APrimalStructureSeating;
struct APrimalStructureShipHull {};
struct APrimalStructureTurret;
struct APrimalStructureTurretBallista;
struct APrimalStructureWaterPipe;
struct APrimalTargetableActor;
struct APrimalWorldSettings;
struct ASceneCapture2D;
struct ASeamlessVolumeManager;
struct AServerStatReplicator;
struct AShipPathManager;
struct AShooterCharacter;
struct AShooterGameMode;
struct AShooterGameSession;
struct AShooterGameState;
struct AShooterHUD;
struct AShooterPlayerController;
struct AShooterPlayerState;
struct AShooterProjectile;
struct AShooterWeapon_Projectile;
struct AShooterWeapon;
struct ASOTFNotification;
struct ASpectatorPawn;
struct AStaticMeshActor;
struct ASupplyCrateSpawningVolume;
struct ATreasureMapManager;
struct AttachLocation;
struct AVolume;
struct AWorldSettings;
struct BitField
{
	DWORD64 offset;
	DWORD bit_position;
	ULONGLONG num_bits;
	ULONGLONG length; //in bytes
};
struct EActorLists {};
struct EActorUpdateOverlapsMethod;
struct EComponentCreationMethod;
struct EDLCSelector {};
struct EInternalObjectFlags;
struct EObjectFullNameFlags;
struct ETravelType;
struct ExpensiveFunctionRegister;
struct F2DByteArray;
struct FActiveEventSupplyCrateWeight {};
struct FActiveForceFeedbackEffect;
struct FActiveHapticFeedbackEffect;
struct FActorBeginCursorOverSignature;
struct FActorBeginOverlapSignature;
struct FActorBeginTouchOverSignature;
struct FActorClassAttachmentInfo {};
struct FActorComponentDeactivateSignature;
struct FActorComponentInstanceData;
struct FActorComponentTickFunction;
struct FActorCustomEventSignature;
struct FActorEndPlaySignature;
struct FActorHitSignature;
struct FActorMatineeUpdated;
struct FActorOnClickedSignature;
struct FActorOnInputTouchBeginSignature;
struct FActorSemaphoreTaken;
struct FActorSpawnParameters;
struct FActorTickFunction;
struct FAdditionalStaticMeshSockets;
struct FAddressInfoResultData;
struct FAdvancedBoneModifierSlider;
struct FAggroEntry;
struct FAIRequestID {};
struct FAmazonS3GetObject;
struct FAnimationEvaluationContext;
struct FAppIDItem;
struct FARKDinoData;
struct FARKTributeData;
struct FARKTributeDino;
struct FArkTributePlayerData;
struct FAssetData;
struct FAssetMatcher;
struct FAssetRegistry;
struct FAsyncSharedLogCleanup;
struct FAsyncUpdatableTexture2D;
struct FAtlasAdminCommandTrackingEntry;
struct FAtlasSaveObjectData;
struct FAttachedInstanced;
struct FAttachedInstancedHarvestingElement;
struct FAttachmentPoint;
struct FAttachmentTransformRules;
struct FAudioDevice;
struct FAvailableMission;
struct FBasedMovementInfo;
struct FBehaviorTreeSearchData;
struct FBlendFilter;
struct FBlueprintCookedComponentInstancingData;
struct FBlueprintTimerDynamicDelegate {};
struct FBodyInstance;
struct FBoid;
struct FBoneDamageAdjuster {};
struct FBoneModifier;
struct FBoneModifierNamed;
struct FBoneModifierRange;
struct FBonePresetSlider;
struct FBoxCenterAndExtent {};
struct FBPNetExecParams;
struct FBroadphaseSettings;
struct FBuffAddition;
struct FBuffStatEntry;
struct FCachedDBAccessor;
struct FCachedTeamTameListStruct;
struct FCanvas
{
	enum EElementType
	{
		ET_Line = 0x0,
		ET_Triangle = 0x1,
		ET_MAX = 0x2,
	};

	enum ECanvasAllowModes
	{
		Allow_Flush = 0x1,
		Allow_DeleteOnRender = 0x2,
	};
};
struct FCDODebugData;
struct FCharacterMovementUpdatedSignature;
struct FCharacterPossessionByPlayer;
struct FCharacterReachedApexSignature;
struct FClassAddition;
struct FClassMapKey;
struct FClassMultiplier;
struct FClassNameReplacement;
struct FClassRedirect;
struct FClassRemapping;
struct FClassRemappingWeight;
struct FCollisionImpactData;
struct FCollisionQueryParams;
struct FCollisionResponseParams;
struct FCollisionResponseSet;
struct FColorDefinition;
struct FCompanionEventData;
struct FCompanionReactionData;
struct FComponentBeginCursorOverSignature;
struct FComponentBeginOverlapSignature;
struct FComponentBeginTouchOverSignature;
struct FComponentEndCursorOverSignature;
struct FComponentEndOverlapSignature;
struct FComponentEndTouchOverSignature;
struct FComponentInstanceDataCache;
struct FComponentOnClickedSignature;
struct FComponentOnInputTouchBeginSignature;
struct FComponentOnInputTouchEndSignature;
struct FComponentOnReleasedSignature;
struct FCompressTaskInfo;
struct FConfigCacheIni;
struct FConfigItemCraftingCostOverride;
struct FConfigMaxItemQuantityOverride {};
struct FConfigNPCSpawnEntriesContainer;
struct FConfigSupplyCrateItemsOverride;
struct FCraftingResourceRequirement;
struct FCrateTemporaryQualityModifierSet;
struct FCropItemPhaseData {};
struct FCryopodPersistantBuffs;
struct FCustomContextMenuData;
struct FCustomContextSubmenu;
struct FCustomItemData;
struct FCustomPropertyConditionState;
struct FCustomTrackedActorInfo;
struct FCustomVersion;
struct FDamageEvent;
struct FDamagePrimalCharacterStatusValueModifier;
struct FDamageTypeAdjuster;
struct FDatabase_AllianceWrapper;
struct FDatabase_ClusterInfo_Server;
struct FDatabase_CreateShapshot;
struct FDatabase_LogEntryWrapper;
struct FDatabase_PlayerJoinedTribe;
struct FDatabase_PlayerRemovedFromTribe;
struct FDatabase_TravelEntry;
struct FDatabase_TribeEntities;
struct FDatabase_TribeWrapper;
struct FDataSet {};
template <typename T>
struct FDataStore;
struct FDebugDisplayInfo;
struct FDebugFloatHistory;
struct FDebugTraceInfo;
struct FDecalData;
struct FDefaultItemEntry;
struct FDialogueContext;
struct FDinoAbilities;
struct FDinoAbilityInfo;
struct FDinoAncestorsEntry;
struct FDinoAncestorsEntryBlueprint;
struct FDinoAttackInfo;
struct FDinoBabySetup;
struct FDinoBaseLevelWeightEntry;
struct FDinoDownloadData;
struct FDinoExtraDefaultItemList;
struct FDinoMapMarkerInfo;
struct FDinoOrderGroup;
struct FDinoSaddleStruct;
struct FDinoSetup;
struct FDinoSetupGroup;
struct FDinoSpawnWeightMultiplier;
struct FDisciplineDefinition;
struct FDiscoveredZone;
struct FDodgeMovementInfo;
struct FDropNoteInfo;
struct FDynamicForceFeedbackDetails;
struct FEmoteGroup;
struct FEngramBuffEntry;
struct FEngramEntries;
struct FEngramEntryAutoUnlock;
struct FEngramEntryOverride;
struct FEngramItemEntry;
struct FEngramStatEntry;
struct FEventItem {};
struct FExplorerNoteAchievement;
struct FExplorerNoteEntry;
struct FExtraEggItem;
struct FFeatCooldown;
struct FFloatingTextEntry;
struct FForceFeedbackValues;
struct FFrame;
struct FGameIniData {};
struct FGameNameRedirect;
struct FGlobalGameplaySetup;
struct FGrappleTether;
struct FGridCellServerInfo;
struct FGrinderItemReplacer;
struct FHairStyleDefinition;
struct FHandIkTarget;
struct FHardwareSurveyResults;
struct FHarvestResourceEntry;
struct FHibernationZoneInfo;
struct FHitResult;
struct FHordeCrateDifficultyLevel;
struct FHordeCrateEvent;
struct FHUDElement {};
struct FInstalledItemInfo;
struct FInstantWeaponData {};
struct FInstigatedAnyDamageSignature;
struct FInteriorSettings;
struct FInvalidReferenceRedirector;
struct FInventoryComponentDefaultItemsAppend;
struct FInventoryItemAdded;
struct FInventoryItemRemoved;
struct FItemAttachmentInfo;
struct FItemCount;
struct FItemCraftingConsumptionReplenishment;
struct FItemCraftingCostOverride;
struct FItemCraftQueueEntry;
struct FItemMaxItemQuantityOverride;
struct FItemMultiplier;
struct FItemNetID;
struct FItemNetInfo;
struct FItemSetup;
struct FItemSlotTypeDefinition;
struct FItemSpawnActorClassOverride;
struct FItemStatGroupValue;
struct FItemStatInfo;
struct FJoinabilitySettings;
struct FJsonObject {};
struct FKey {};
struct FLandedSignature;
struct FLatentActionInfo {};
struct FLatestMissionScore {};
struct FLayerNameArray;
struct FLeaderboardEntry {};
struct FLeaderboardRow {};
struct FLeaderboardsContainer;
struct FLevelActorVisibilityState {};
struct FLevelExperienceRamp;
struct FLifetimeProperty {};
struct FLocalizedSoundCueEntry;
struct FLocalizedSoundWaveAnimTexturePairArrays;
struct FLockedFeat;
struct FLocRot;
struct FMassTeleportData {};
struct FMatineeActorFinished;
struct FMatineeActorStopped;
struct FMaxItemQuantityOverride {};
struct FMaxStatScaler;
struct FMeleeHitInfo;
struct FMemoryArchive;
struct FMemoryReader;
struct FMemoryWriter;
struct FMinimalViewInfo;
struct FMissionAlertEntry;
struct FMissionGlobalData {};
struct FMissionMetaData;
struct FMissionTriggerBeginOverlap;
struct FMissionTriggerEndOverlap;
struct FMissionWaypointInfo {};
struct FModuleManager;
struct FMovementModeChangedSignature;
struct FMultiAchievement;
struct FMultiUseEntry;
struct FMultiUseWheelOption;
struct FNamedTeamDefinition;
struct FNavAgentProperties;
struct FNetChangeDefaultPropertyValue;
struct FNetDriverDefinition;
struct FNetExecParams;
struct FNetViewer;
struct FNetworkGUID {};
struct FNetworkPredictionData_Client_Character;
struct FNetworkPredictionData_Client;
struct FNetworkPredictionData_Server_Character;
struct FNetworkPredictionData_Server;
struct FNotifyAddPassenger;
struct FNotifyClearPassenger;
struct FNotifyClearRider;
struct FNotifyFlyerLanded;
struct FNotifySetRider;
struct FNPCSpawnEntriesContainerAdditions;
struct FNXSettings;
struct FObjectCorrelation;
struct FObjectInitializer;
struct FObjectInstancingGraph;
struct FObjectPreSaveContext;
struct FObjectReader;
struct FObjectWriter;
struct FOceanHarvestedEntry;
struct FOceanHarvestEntry;
struct FOctreeElementSimple;
struct FOnAddNewTribe;
struct FOnClearMountedDino;
struct FOnDinoDownloaded;
struct FOnDinoUploaded;
struct FOnHTTPGetProcessed;
struct FOnHTTPPostResponse;
struct FOnKilled;
struct FOnlineAchievementsWrite;
struct FOnlineSessionSearchResult;
struct FOnNotifyDamage;
struct FOnPlayerListReady;
struct FOnPlayerStatePawnSet;
struct FOnPossessedPawnChanged;
struct FOnPostLogin;
struct FOnRemovePlayerFromTribe;
struct FOnRemoveTribe;
struct FOnSerializeForSaveFile;
struct FOnServerChatMessage;
struct FOnServerDirectMessage;
struct FOnServerNotification;
struct FOnServerTraveFPropertyWrapperlStarted;
struct FOnSetMountedDino;
struct FOnStartNewPlayer;
struct FOpenColorIODisplayConfiguration;
struct FOrderingGroupInfo;
struct FOutBunch;
struct FOutParmRec;
struct FOutputDeviceFile;
struct FOverlapInfo;
struct FOverlapResult;
struct FOverrideAnimBlueprintEntry;
struct FPaintItem {};
struct FPenetrationTraceHit;
struct FPingData {};
struct FPlacementData;
struct FPlayerBanInfo;
struct FPlayerBoneBodyPreset;
struct FPlayerCharacterGenderDefinition;
struct FPlayerConfigVoiceCollectionInfo;
struct FPlayerDeathReason;
struct FPlayerDynamicMaterialColors;
struct FPlayerDynamicMaterialFloat;
struct FPlayerDynamicMaterialVector;
struct FPlayerFlagData;
struct FPlayerLocatorEffectMap;
struct FPlayerMuteList {};
struct FPlayersAwaitingUpdatedCachedTeamTameListStruct;
struct FPluginRedirect;
struct FPointDamageEvent;
struct FPointLightReductionSettings;
struct FPointOfInterestCompanionBehavior;
struct FPointOfInterestData_ForCompanion;
struct FPointOfInterestData;
struct FPorthole;
struct FPostProcessMaterialAdjuster;
struct FPostProcessOverlapEvent;
struct FPredictProjectilePathParams;
struct FPredictProjectilePathResult;
struct FPreSpawnedDino;
struct FPrimalCameraInterpParams;
struct FPrimalCameraParams;
struct FPrimalCharacterNotifyAttackEnded;
struct FPrimalCharacterNotifyAttackStarted;
struct FPrimalCharacterStatusStateDefinition;
struct FPrimalCharacterStatusStateThresholds;
struct FPrimalCharacterStatusValueDefinition;
struct FPrimalCharacterStatusValueModifier;
struct FPrimalEquipmentDefinition;
struct FPrimalItemDefinition;
struct FPrimalItemQuality;
struct FPrimalItemStatDefinition;
struct FPrimalMapMarkerEntryData;
struct FPrimalPersistentCharacterStatsStruct;
struct FPrimalPlayerCharacterConfigStruct;
struct FPrimalPlayerCharacterConfigStructReplicated;
struct FPrimalPlayerDataStruct;
struct FPrimalSaddleStructure {};
struct FPrimalSnapshotPose {};
struct FPrimalStatGroupDefinition;
struct FPrimalStructureSnapPoint;
struct FPrimalStructureSnapPointOverride;
struct FPrimalWirelessReferences;
struct FPrimaryAssetId;
struct FProcHandle;
struct FProjectileArc;
struct FProjectileWeaponData;
struct FPropertyModificationsTracker;
struct FPropertyWrapper;
struct FPubSub_TribeNotification_Chat;
struct FQualityTierCraftingResourceRequirements;
struct FQueuedThreadPool;
struct FRadialDamageEvent {};
struct FRangedValues;
struct FRecoveryRateOverride;
struct FReferenceCollector;
struct FRegionGeneralOverrides;
struct FRegisterComponentContext;
struct FRelativePositionEntry {};
struct FRenderCommandFence;
struct FRepAttachment;
struct FReplicatedBasedMovementInfo;
struct FReplicatedFoliageOverride;
struct FReplicatedGrappleTetherData;
struct FReplicatePingData {};
struct FReplicationFlags;
struct FRepMovement;
struct FRepRecord;
struct FRepRootMotionMontage;
struct FResourceTemporaryAmountModifierSet;
struct FReverbSettings;
struct FRHITexture2D;
struct FRigidBodyCollisionInfo;
struct FRigidBodyErrorCorrection;
struct FRootMotionMovementParams;
struct FRootMotionSourceGroup;
struct FRotationConversionCache;
struct FRotator_NetQuantize;
struct FRotator_NetQuantizeSmartPitch;
struct FSaddlePassengerSeatDefinition {};
struct FScreenMessageString;
struct FScreenSaverInhibitor;
struct FSeamlessIslandInfo;
struct FSeamlessTravelHandler;
struct FSeamlessTravelPlayerData;
struct FSemaphoreEntry;
struct FServerCustomFolder;
struct FServerOptions {};
struct FServerTribeAtMax;
struct FShipTypeDisplayInformation;
struct FShooterCharacterDied;
struct FShooterCharacterSpawned;
struct FShooterGameSessionParams;
struct FShooterOnlineSearchSettings;
struct FShooterOnlineSessionSettings;
struct FShooterSessionData;
struct FShorelineMetadata;
struct FShorelineProps;
struct FShownTreasureData;
struct FSimulatedRootMotionReplicatedMove;
struct FSlateBrush;
struct FSlateColor {};
struct FSlotAnimationTrack;
struct FSoftClassPath;
struct FSoilTypeDescription;
struct FSoilTypeRegionMapping;
struct FSpawnPointInfo;
struct FStasisGrid;
struct FStatColorMapping;
struct FStatusValueModifierDescription;
struct FStatValPair;
struct FStatValuePair {};
struct FSteamInventoryItemInfo {};
struct FStoredMoveData;
struct FStreamableManager;
struct FStreamableRenderResourceState;
struct FStructRedirect;
struct FStructureToBuildAddition;
struct FStructureVariant {};
struct FStructureVariantAddition;
struct FSubtitleStringMap;
struct FSupplyCrateItemSet;
struct FSupplyCrateSpawnEntry;
struct FSupplyCrateSpawnPointEntry;
struct FSupplyCrateValuesOverride;
struct FTakePointDamageSignature;
struct FTameUnitCounts {};
struct FTamingDinoInfo;
struct FTargetingTeamChanged {};
struct FTeamPingData;
struct FTeleportDestination {};
struct FTexture2DResourceMem;
struct FTexturePlatformData;
struct FTextureResource;
struct FTickCallbacks;
struct FTickFunction;
struct FTimerHandle;
struct FTimerManager;
struct FTopLevelAssetPath;
struct FTraceDatum;
struct FTraceHandle;
struct FTrackedActorPlusInfoStruct;
struct FTrackedActorWaypointInfo;
struct FTransformedSubLevel;
struct FTransponderInfo {};
struct FTreeStumpCreationTime;
struct FTribeAlliance;
struct FTribeData;
struct FTribeEntity;
struct FTribeGovernment;
struct FTribeLogEntry;
struct FTribeNotification;
struct FTribeRankGroup;
struct FTribeTravelCount;
struct FTribeWar;
struct FTributePlayerTribeInfo;
struct FTutorialDefinition;
struct FUniqueNetId;
struct FUniqueNetIdRepl;
struct FUniqueNetIdUInt64;
struct FUniqueNetIdWrapper;
struct FUnlockableEmoteEntry;
struct FUnreplicatedEggData;
struct FUseItemAddCharacterStatusValue;
struct FVector_NetQuantize;
struct FVector_NetQuantize100;
struct FVector_NetQuantizeNormal;
struct FViewport;
struct FVirtualTextureBuildSettings;
struct FWalkableSlopeOverride;
struct FWeaponAttack {};
struct FWeaponData {};
struct FWeaponEvent {};
struct FWeightedObjectList;
struct FWildFollowerSpawnEntry;
struct FWorldBuffPersistantData;
struct FWorldBuffTrackerItem;
struct FWorldContext;
struct FWorldDefaultItemSet;
struct FWriteFileTaskInfo;
struct Globals;
struct IDataLayerWatcher;
struct IDataListEntryInterface;
struct IEngineLoop;
struct IHeadMountedDisplay;
struct IHttpRequest;
struct IOnlineSubsystem {};
struct IPathFollowingAgentInterface;
struct IRepChangedPropertyTracker;
struct IStereoRendering;
struct ITargetableInterface;
struct LocationQueue;
struct PingAvgData;
struct RCONClientConnection;
struct RCONPacket;
struct UActorChannel;
struct UActorComponent;
struct UActorSequenceComponent;
struct UAllClustersInventory {};
struct UAnimationAsset;
struct UAnimMontage;
struct UAnimNotify;
struct UAnimNotifyState;
struct UAnimSequence;
struct UAnimSequenceBase;
struct UAntiDupeTransactionLog;
struct UAssetUserData;
struct UAsyncPhysicsData;
struct UAsyncPhysicsInputComponent;
struct UAudioComponent;
struct UBehaviorTree;
struct UBlueprintCore;
struct UBookmarkBase;
struct UBoxComponent;
struct UBrainComponent;
struct UCanvas;
struct UCapsuleComponent;
struct UChannel {};
struct UCharacterMovementComponent;
struct UCheatManager;
struct UCheatManagerExtension;
struct UChildActorComponent;
struct UClass;
struct UConsole;
struct UDamageType;
struct UDatabase_LoginData;
struct UDatabase_PubSub_GeneralNotifications;
struct UDatabase_RemoteFileManager;
struct UDatabase_SharedLog;
struct UDatabase_TerritoryMap;
struct UDatabase_TravelData;
struct UDatabase_TribeDataManager;
struct UDataLayerAsset;
struct UDataLayerInstance;
struct UDataTable;
struct UDeferredMovementContext;
struct UDeviceProfileManager;
struct UDialogueWave;
struct UDiscoveryZoneDataListEntry;
struct UEngine;
struct UField;
struct UFoliageType;
struct UFont {};
struct UFunction;
struct UFXSystemComponent;
struct UGameEngine;
struct UGameInstance;
struct UGameplayStatics;
struct UGameServerQuerySubsystem;
struct UGameUserSettings;
struct UGenericDataListEntry;
struct UHexagonTradableOption {};
struct UHierarchicalInstancedStaticMeshComponent;
struct UInputComponent;
struct UInstancedStaticMeshComponent;
struct UInterface;
struct UInterpTrackInstDirector;
struct ULeaderboard {};
struct ULevel;
struct ULevelBase;
struct ULevelVariantSets;
struct ULocalMessage;
struct ULocalPlayer;
struct UMaterial;
struct UMaterialInstanceConstant;
struct UMaterialInstanceDynamic;
struct UMaterialInterface;
struct UMaterialParameterCollection;
struct UMeshComponent;
struct UModDataAsset;
struct UMovementComponent;
struct UMovieScene;
struct UMovieSceneControlRigParameterTrack;
struct UMovieSceneSequence;
struct UMovieSceneTrack;
struct UNavigationSystemConfig;
struct UNetConnection;
struct UNetDriver;
struct UNiagaraComponent;
struct UNiagaraEmitter;
struct UNiagaraSystem;
struct UObject;
struct UObjectBase_vtbl;
struct UObjectBase;
struct UObjectBaseUtility;
struct UObjectSerializer;
struct UPaintingCache;
struct UPaintingStreamingComponent;
struct UPaintingTexture;
struct UParticleSystem;
struct UParticleSystemComponent;
struct UPawnMovementComponent;
struct UPendingNetGame;
struct UPhysicalMaterial;
struct UPlayer;
struct UPlayerInput {};
struct UPrimalAIState;
struct UPrimalAssets;
struct UPrimalBuffPersistentData;
struct UPrimalCableComponent;
struct UPrimalCharacterStatusComponent;
struct UPrimalColorSet {};
struct UPrimalDinoEntry;
struct UPrimalDinoSettings;
struct UPrimalEngramEntry;
struct UPrimalGameData;
struct UPrimalGlobals;
struct UPrimalGlobalUIData;
struct UPrimalHarvestingComponent;
struct UPrimalInventoryComponent;
struct UPrimalItem_Dye;
struct UPrimalItem_Shield;
struct UPrimalItem;
struct UPrimalLocalProfile;
struct UPrimalNavigationInvokerComponent;
struct UPrimalPlayerData;
struct UPrimalStructureSettings;
struct UPrimalStructureSnapSettings;
struct UPrimalStructureToolTipWidget;
struct UPrimalSupplyCrateItemSets;
struct UPrimalUI;
struct UPrimalWindSourceComponent;
struct UPrimalWirelessExchangeData;
struct UPrimalWorldBuffData;
struct UPrimalWorldSettingsEventOverrides {};
struct UPrimaryDataAsset;
struct UPrimitiveComponent;
struct UProperty;
struct UPubSub_GeneralNotifications;
struct UPubSub_TribeNotifications;
struct URCONServer;
struct USaveGame;
struct USceneComponent;
struct USeamlessDataServer;
struct UShapeComponent;
struct UShooterCheatManager;
struct UShooterDamageType;
struct UShooterGameInstance;
struct UShooterGameUserSettings;
struct UShooterHaptics;
struct UShooterPersistentUser {};
struct USkeletalMesh;
struct USkeletalMeshComponent;
struct USoundAttenuation;
struct USoundBase;
struct USoundClass;
struct USoundConcurrency;
struct USoundCue;
struct USoundMix;
struct USoundSubmix;
struct USoundWave;
struct USphereComponent;
struct USplineComponent;
struct UStaticMesh;
struct UStaticMeshComponent;
struct UStaticMeshSocket;
struct UStruct;
struct UStructurePaintingComponent {};
struct UTexture;
struct UTexture2D;
struct UTireType;
struct UToolTipWidget;
struct UTriggerEffectLibrary;
struct UUI_CustomOverlay;
struct UUI_GenericConfirmationDialog;
struct UUI_HostSession;
struct UUI_Notification;
struct UUI_XBoxFooter;
struct UUserWidget {};
struct UWaveWorksComponent;
struct UWeaponAttackData;
struct UWidget;
struct UWorld;
struct UWorldPartition;

// Address helpers
ARK_API DWORD64 GetAddress(const void* base, const std::string& name);
ARK_API LPVOID GetAddress(const std::string& name);

ARK_API LPVOID GetDataAddress(const std::string& name);

ARK_API BitField GetBitField(const void* base, const std::string& name);
ARK_API BitField GetBitField(LPVOID base, const std::string& name);

#define DECLARE_HOOK(name, returnType, ...) typedef returnType(__fastcall * name ## _Func)(__VA_ARGS__); \
inline name ## _Func name ## _original; \
returnType __fastcall Hook_ ## name(__VA_ARGS__)